### ISSUE TITLE
Add a link for the "production" canvas URL somewhere in Editor

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3696] opened 2022-04-14 19:20 UTC
Users can click on the `...` menu in handlers to get a link to the handler, but we don't have that link presented anywhere more obvious. We should add a link, maybe in the menu?

**Comment by StachuDotNet** [comment] 2022-06-24 01:52
Closing - duplicate of #4121 (which had a bit more information)

**Closed by StachuDotNet** 2022-06-24 01:52 UTC
Labels: good-first-bug, contributor-friendly, component:editor
