### ISSUE TITLE
Add support for infinite precision integers

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2544] opened 2020-06-07 20:25 UTC
Our integers are currently 63-bit ints. We would like them to be infinite precision. this is not actually all that complicated:

- replace the contents of DInt with zarith (OCaml infinite int library)
- make Zarith work with the js_of_ocaml build
- remove the parts of the client that limit integers to 18/19 digits
- figure out how the serialization between the server and the client works (using yojson's <code>`IntLit</code>, probably)

**Comment by StachuDotNet** [comment] 2024-01-09 20:17
Duplicate of #3279

**Closed by StachuDotNet** 2024-01-09 20:17 UTC
Labels: component:language
