### ISSUE TITLE
JWT JSON parser doesn't support NaN well

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3662] opened 2022-04-07 15:00 UTC
Title to be adjusted once we understand a bit better.

After creating two Secrets, I went to test `signAndEncodeWithHeaders_v1` with

```
let payload = "testing"
let headers = {
                a : 0.0 / 0.0
              }
let encoded = JWT::signAndEncodeWithHeadersv1 RSA_PRIVATE_KEY headers payload
let decoded = JWT::verifyAndExtractv1 RSA_PUBLIC_KEY encoded
payload == decoded.payload
```
intending to cause an error, to "see what would happen".

Tested both locally and on prod (against F# backend)

Since doing this, regardless of how many times I refresh, or change code to something OK, I'm presented with a spinner next to the REPL and an error at the bottom of my screen - the only way to move forward would be to copy/paste into a new REPL, as far as I'm seeing. Even replacing the REPL's body with "test" doesn't help - still trying its best to load traces.

A rollbar was made around this: https://rollbar.com/darkops/darklang/items/2977/

Edit: to be clear, this happens with other (non `NaN`) headers.
For example, `DObj (map [("", DUuid 779f0408-091d-f0e2-047a-460b2da3c591)]);
  DFloat 2.718281828])` fails

**Comment by StachuDotNet** [comment] 2022-04-07 15:02
![image](https://user-images.githubusercontent.com/906686/162230251-58f4dbaf-0887-46dd-b9d0-d6a026955510.png)

**Comment by pbiggar** [comment] 2022-04-14 20:33
I can make this happen with a NaN. The problem there is that the JSON parser doesn't like the NaN we send up from the frontend. This is fixable, but the same problem exists on the ocaml backend so I wouldn't make this a priority right now.

However, I couldn't follow what the issue is with `DObj (map [("", DUuid 779f0408-091d-f0e2-047a-460b2da3c591)]); DFloat 2.718281828])` - I can't actually tell what that is. I tried

```
Dict::empty
|> Dict::set "" String::toUUIDv1 "779f0408-091d-f0e2-047a-460b2da3c591"
```

but i couldn't see how the float fit into it? I also tried with the float instead of the UUID and it seemed to work fine.

Note that I wasn't using a valid RSA key, but I did try putting it in a secret.

Any pointers on getting this to reproduce?

**Comment by StachuDotNet** [comment] 2022-04-14 22:00
The Float there was for the payload param, and is `e` - found via a fuzztest

I can't seem to reproduce that now, actually. I'd say fine to ignore.

> This is fixable, but the same problem exists on the ocaml backend so I wouldn't make this a priority right now.
Agreed, I'm OK with this issue closing then

**Comment by pbiggar** [comment] 2022-04-14 22:10
We can leave it open, since it's still a problem. Just don't need to do it for BwdServer to ship.

**Comment by pbiggar** [comment] 2023-03-01 04:52
Closing as it doesn't apply to darklang-next

**Closed by pbiggar** 2023-03-01 04:52 UTC
Labels: project:complete-fsharp-migration
