### ISSUE TITLE
Rollbar: "Deadline Exceeded" in EventQueueV2 `dequeue`

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3816] opened 2022-05-17 03:12 UTC
https://rollbar.com/darkops/darklang/items/3236/

https://github.com/darklang/dark/blob/4a9fdbede527bc00d08b08f6ece456cf135d7733/fsharp-backend/src/LibBackend/EventQueueV2.fs#L275

**Comment by pbiggar** [comment] 2022-05-17 04:10
Duplicate of #3815

**Closed by pbiggar** 2022-05-17 04:10 UTC
