### ISSUE TITLE
Can't type when dependant variable has been deleted

### ISSUE THREAD

**Issue by Diederikjh** [darklang/dark#4321] opened 2022-07-20 19:32 UTC
Steps to repdocue:

Create a function with some variables with dependencies:
```
let s1 = p1 ++ "afsafsadf"
let s2 = s1 ++ "aXXXXX"
```

Selecte whole line that s1 is on.
Delete the line
s1 variable dissapears - this is expected.
Click on empty box where s1 used to be.
Start typing new variable name (like one you want to replace s1 with) - notice that key presses (letters atleast) are ingored.
Double quote, and numbers seem to enter correctly.

Smallish UI niggle that I found recently.

**Comment by pbiggar** [comment] 2022-07-21 03:39
Reproduced.

<img width="525" alt="image" src="https://user-images.githubusercontent.com/181762/180124822-fea0526f-6eea-42d0-b31d-453d47ec2496.png">

It looks like there's a variable named string `""`

<img width="758" alt="image" src="https://user-images.githubusercontent.com/181762/180124968-60fe5020-29b6-4221-bcee-bef156304a5d.png">

**Comment by pbiggar** [comment] 2023-03-01 04:40
Closing as it doesn't apply to darklang-next

**Closed by pbiggar** 2023-03-01 04:40 UTC
Labels: good-first-bug, component:fluid
